// Human-readable language-specific editorial source; no runtime credentials.
export const languages = {
  zh: {
    titles: ['ElevenLabs + Kasamila：视觉与声音统一的视频电话客服', 'OBS + Kasamila + Streamlabs：一套组件实现数字人直播'],
    summaries: ['保留现有 ElevenLabs Agent，给客服回答加上可见数字人；让回复音频播放与口型使用同一条链路。', '透明浏览器源、音频输入、队列、打断、场景切换与明确结束，让四类直播共用数字人主持底层。'],
    steps: [
      ['先配置现有 ElevenLabs Agent：知识库、客服指令、工具权限和人工升级流程仍在原 Agent 中。数字人不替换业务逻辑。', '在样例目录 npm ci，复制 .env.example 为 .env。服务端设置 PROVIDER=elevenlabs、ELEVENLABS_API_KEY、ELEVENLABS_AGENT_ID，以及 Kasamila Key、模板 ID、严格匹配的媒体描述符；输入输出选择 PCM。', '运行 npm start，打开 /public/video-call.html。点击 Start 解锁声音并授权麦克风。服务端获取 ElevenLabs 签名会话地址，永久 Key 和该签名地址都不交给浏览器。', '麦克风只进入语音 Agent；Agent 回复的实际 PCM 样本交给 Kasamila 同时播放并驱动口型，不另开平台播放器。可选来电摄像头只做本地预览，不上传；本页面不是已实现的真人 WebRTC 或 PSTN 电话。', '用户抢话时废弃旧回复队列；手动清队列不保证上游生成已停止。通话结束点击 End，关闭平台链路、destroy 数字人并请求授权 Runtime 结束。静音或关闭声音不是停止计费；结束失败应检查授权控制界面。'],
      ['先启动共享 relay，选择一个语音 Agent 或认证 PCM bridge。设置 KASAMILA_OUTPUT_MODE=transparent，使用支持透明模板的 packed-matte HLS；普通视频加 CSS 透明度不能替代真正透明输出。', '普通浏览器打开 /public/studio.html，创建房间并复制临时显示 URL。OBS 添加 Browser Source；Streamlabs Desktop 用自己的 Browser Source 加同一 URL。二者是替代宿主，不必同时运行。', '使用来源 Interact 点击 Enable audio，再从控制台 Start。麦克风在控制台采集；Agent 回复才驱动数字人。OBS 开启控制浏览器音频，避免同时捕获桌面声音造成双重播放。', '完整音频文件按 FIFO 排队，最多四个、每个 3 MiB / 30 秒；打断废弃旧队列。娱乐、聊天、电商、游戏只是同一组件的四种布局。可选 OBS WebSocket v5 通过服务端密码切换真实 Program Scene，不冒称 Streamlabs Desktop 同样支持该 RPC。', '可选 Streamlabs Socket API 把事件摘要送到控制台审核，不能把打赏正文自动变成提示词或播报。来源隐藏、停用、断连或点击 End 都触发结束，重新显示不自动开计费。保留结束确认；机器崩溃仍依赖租约到期。']
    ],
    notes: ['这是可运行的 AI 视频电话式样例，不是平台生产认证，也不保证精确音素。正式服务还需登录、用户/模板授权、HTTPS/WSS、隐私同意、CRM 工具权限和带真实账户的多轮抢话验收。', '这是一套可嵌入的主持底层，不包含四套业务产品。公开网关需登录、Origin 校验、配额、审核和 HTTPS/WSS；透明背景、队列、转场及明确结束应在真实 OBS/Streamlabs 环境验收。'],
    labels: ['实施步骤', '边界与验收', '代码与协议', 'Markdown / AI 阅读']
  },
  en: {
    titles: ['ElevenLabs + Kasamila: video-call customer service with one voice and visual path', 'OBS + Kasamila + Streamlabs: one embeddable avatar host for livestreaming'],
    summaries: ['Keep your existing ElevenLabs Agent and give its customer-service replies a visible avatar, using one audio path for sound and mouth motion.', 'Transparent Browser Sources, audio input, queues, interruption, scene layouts and explicit session termination share one host component.'],
    steps: [
      ['Configure your existing ElevenLabs Agent with its knowledge base, service instructions, authorized tools and human escalation. The avatar does not replace your business logic.', 'Run npm ci in the sample directory and copy .env.example to .env. Set backend-only PROVIDER=elevenlabs, ELEVENLABS_API_KEY, ELEVENLABS_AGENT_ID and the Kasamila key, accessible template ID and matching canonical media descriptor. Select PCM input and output.', 'Run npm start and open /public/video-call.html. Click Start to unlock audio and permit the microphone. Your backend obtains the signed ElevenLabs conversation URL; neither it nor permanent provider keys go to the browser.', 'The microphone reaches the voice agent only. Its actual reply PCM reaches Kasamila for BOTH playback and mouth inference; do not add a second provider audio player. Optional caller-camera preview stays local. This UI is not a completed human WebRTC call or PSTN service.', 'Barge-in invalidates old playback. Manual queue clearing does not guarantee upstream generation has stopped. End closes the provider transport, destroys the avatar and requests authorized Runtime termination. Silence is not a billing stop; investigate an unconfirmed end request.'],
      ['Start the shared relay with one voice agent or the authenticated PCM bridge. Set KASAMILA_OUTPUT_MODE=transparent and provide the packed-matte HLS descriptor of a transparent-capable template. CSS opacity cannot remove an ordinary video background.', 'Open /public/studio.html in a normal browser, create a room and copy its temporary display URL. Add an OBS Browser Source, or the same URL to Streamlabs Desktop Browser Source. They are alternative hosts, not a requirement to run both applications.', 'Use source Interact to click Enable audio before Start in studio. Capture microphone input in studio; only agent replies drive the avatar. Route browser audio through OBS and avoid also capturing the same desktop audio.', 'Complete files use FIFO order: four items, <=3 MiB and <=30 seconds each. Interrupt discards stale playback. Entertainment, chat, commerce and game are layouts of one host. Optional server-side OBS WebSocket v5 switches the real Program Scene; this does not imply a matching Streamlabs Desktop RPC.', 'Optional Streamlabs Socket API events become operator-reviewed summaries, never automatic donor-message prompts or speech. Hiding, deactivating, disconnecting or End releases the session; showing the source does not automatically restart billing. Check the end acknowledgement; machine failure still relies on lease expiry.']
    ],
    notes: ['This is a runnable AI video-call-style starter, not vendor production certification or a phoneme-accuracy guarantee. Add login, template authorization, HTTPS/WSS, consent and CRM/tool controls; test real accounts, multi-turn speech and interruption.', 'This is one embeddable host, not four finished business products. A public gateway needs login, origin checks, quotas, moderation and HTTPS/WSS. Verify transparency, queues, transitions and explicit termination in your actual broadcast setup.'],
    labels: ['Implementation', 'Boundaries and acceptance', 'Code and protocols', 'Markdown / AI reading']
  },
  fr: {
    titles: ['ElevenLabs + Kasamila : service client en appel vidéo, voix et image unifiées', 'OBS + Kasamila + Streamlabs : un composant commun pour les directs avec avatar'],
    summaries: ['Conservez votre Agent ElevenLabs et rendez ses réponses visibles, avec un seul chemin audio pour la voix et les mouvements de bouche.', 'Source transparente, entrée audio, file de lecture, interruption, scènes et fin de session dans un seul composant.'],
    steps: [
      ['Configurez votre Agent ElevenLabs existant : base de connaissances, consignes, outils autorisés et transfert humain. L’avatar ne remplace pas cette logique.', 'Exécutez npm ci et copiez .env.example vers .env. Gardez côté serveur PROVIDER=elevenlabs, ELEVENLABS_API_KEY, ELEVENLABS_AGENT_ID et les paramètres Kasamila. Utilisez un modèle accessible, son descripteur média exact et des entrées/sorties PCM.', 'Lancez npm start puis /public/video-call.html. Start débloque le son et demande le microphone. Le serveur obtient l’URL signée ElevenLabs ; ni cette URL ni les clés permanentes ne vont au navigateur.', 'Le microphone alimente uniquement l’agent. Sa réponse PCM est lue et anime la bouche par le même SDK Kasamila, sans second lecteur. La caméra facultative reste locale ; cette interface n’est pas un appel WebRTC humain ou un service PSTN complet.', 'La prise de parole interrompt la lecture ancienne. Vider la file manuellement ne garantit pas l’arrêt de la génération distante. End ferme le transport, détruit l’avatar et demande la fin autorisée du Runtime. Le silence n’arrête pas la facturation ; vérifiez la confirmation.'],
      ['Lancez le relais avec un agent ou le pont PCM authentifié. Choisissez KASAMILA_OUTPUT_MODE=transparent et le HLS packed-matte d’un modèle compatible ; l’opacité CSS ne suffit pas.', 'Ouvrez /public/studio.html, créez une salle et copiez son URL temporaire. Ajoutez une source navigateur OBS ou Streamlabs Desktop : ce sont deux hôtes alternatifs.', 'Dans Interact, cliquez Enable audio avant Start dans le studio. Le microphone est capturé dans le studio ; seules les réponses animent l’avatar. Évitez de doubler le son navigateur avec le son du bureau.', 'La file FIFO accepte quatre fichiers complets, chacun limité à 3 MiB et 30 secondes. Interrupt élimine les anciens éléments. Divertissement, discussion, commerce et jeu sont quatre dispositions du même hôte. Le RPC OBS WebSocket v5 facultatif change la vraie scène Program, sans promettre le même RPC dans Streamlabs Desktop.', 'Les événements Streamlabs facultatifs deviennent des résumés à vérifier, jamais des instructions ou paroles automatiques issues des dons. Masquer, désactiver, déconnecter ou End termine la session ; la réapparition ne relance pas automatiquement la facturation. Vérifiez la fin ; une panne dépend encore de l’expiration du bail.']
    ],
    notes: ['Cet exemple exécutable n’est ni une certification fournisseur ni une garantie phonétique. Ajoutez authentification, consentement, autorisation des modèles et outils, HTTPS/WSS et tests réels de conversation.', 'Un hôte commun ne constitue pas quatre produits métier. Ajoutez contrôle d’origine, quotas et modération ; validez transparence, files, transitions et fin de session dans votre installation réelle.'],
    labels: ['Mise en œuvre', 'Limites et validation', 'Code et protocoles', 'Lecture Markdown / IA']
  },
  de: {
    titles: ['ElevenLabs + Kasamila: Video-Kundendienst mit gemeinsamem Ton- und Bildpfad', 'OBS + Kasamila + Streamlabs: ein Avatar-Host für viele Livestreams'],
    summaries: ['Den bestehenden ElevenLabs Agent behalten und seine Antworten sichtbar machen: Wiedergabe und Mundbewegung nutzen denselben Audiopfad.', 'Transparente Browserquelle, Audioeingang, Warteschlange, Unterbrechung, Szenen und Sitzungsende in einer Komponente.'],
    steps: [
      ['Konfigurieren Sie den bestehenden ElevenLabs Agent: Wissensbasis, Service-Regeln, erlaubte Werkzeuge und menschliche Eskalation bleiben dort. Der Avatar ersetzt diese Logik nicht.', 'npm ci ausführen und .env.example nach .env kopieren. PROVIDER=elevenlabs, ELEVENLABS_API_KEY, ELEVENLABS_AGENT_ID sowie Kasamila-Zugang und passenden Mediendeskriptor nur serverseitig setzen. PCM für Ein- und Ausgabe wählen.', 'npm start ausführen und /public/video-call.html öffnen. Start entsperrt Audio und fragt nach dem Mikrofon. Der Server beschafft die signierte ElevenLabs-URL; permanente Schlüssel und diese URL bleiben vom Browser fern.', 'Das Mikrofon geht nur zum Agent. Die echte PCM-Antwort wird vom selben Kasamila SDK abgespielt und für Mundbewegungen genutzt, ohne zweiten Player. Die optionale Kamera bleibt lokal; dies ist kein fertiger menschlicher WebRTC- oder PSTN-Dienst.', 'Dazwischenreden verwirft alte Wiedergabe. Manuelles Leeren stoppt nicht garantiert die entfernte Generierung. End schließt den Transport, zerstört den Avatar und fordert das autorisierte Runtime-Ende an. Stille beendet keine Abrechnung; Bestätigung prüfen.'],
      ['Relay mit einem Agent oder authentifizierten PCM-Bridge starten. KASAMILA_OUTPUT_MODE=transparent und echtes packed-matte HLS verwenden; CSS-Deckkraft ersetzt keinen transparenten Videohintergrund.', 'In /public/studio.html einen Raum erstellen und die temporäre Anzeige-URL kopieren. OBS Browser Source oder Streamlabs Desktop Browser Source verwenden; beides sind alternative Hosts.', 'Über Interact zuerst Enable audio, danach Start im Studio. Das Studio nimmt das Mikrofon auf, nur Antworten bewegen den Avatar. Browser- und Desktop-Audio nicht doppelt erfassen.', 'FIFO erlaubt vier vollständige Dateien mit jeweils höchstens 3 MiB und 30 Sekunden. Interrupt verwirft alte Elemente. Unterhaltung, Chat, Handel und Spiel sind Layouts desselben Hosts. Optional schaltet OBS WebSocket v5 die echte Program-Szene; das verspricht keinen entsprechenden Streamlabs-Desktop-RPC.', 'Optionale Streamlabs-Ereignisse werden zur Prüfung angezeigt, nicht automatisch als Spenden-Prompts gesprochen. Verbergen, Deaktivieren, Trennen oder End beendet die Sitzung; Sichtbarkeit startet keine Abrechnung neu. Ende bestätigen; bei Rechnerausfall gilt weiterhin die Lease-Frist.']
    ],
    notes: ['Ein ausführbares Beispiel ist keine Anbieterzertifizierung oder Phonem-Garantie. Login, Vorlagenrechte, Einwilligung, Werkzeugrechte und HTTPS/WSS ergänzen; echte Gespräche und Unterbrechungen testen.', 'Eine Host-Komponente ist nicht vier fertige Geschäftsprodukte. Origin-Prüfung, Quoten und Moderation ergänzen; Transparenz, Warteschlangen, Übergänge und Ende real testen.'],
    labels: ['Umsetzung', 'Grenzen und Abnahme', 'Code und Protokolle', 'Markdown / KI-Lektüre']
  },
  ru: {
    titles: ['ElevenLabs + Kasamila: видеоподдержка с единым трактом голоса и изображения', 'OBS + Kasamila + Streamlabs: один компонент ведущего для трансляций'],
    summaries: ['Сохраните существующего ElevenLabs Agent и добавьте видимого аватара: звук и движение рта получают одну аудиодорожку.', 'Прозрачный Browser Source, аудиовход, очередь, прерывание, сцены и явное завершение сеанса в одном компоненте.'],
    steps: [
      ['Настройте существующего Agent ElevenLabs: база знаний, правила поддержки, разрешённые инструменты и передача человеку остаются в нём. Аватар не заменяет бизнес-логику.', 'Выполните npm ci и скопируйте .env.example в .env. Задайте только на сервере PROVIDER=elevenlabs, ELEVENLABS_API_KEY, ELEVENLABS_AGENT_ID и параметры Kasamila с точным описателем медиашаблона. Выберите PCM для входа и выхода.', 'Запустите npm start и откройте /public/video-call.html. Start разрешает звук и запрашивает микрофон. Сервер получает подписанный URL ElevenLabs; постоянные ключи и этот URL не передаются браузеру.', 'Микрофон отправляется только агенту. PCM его ответа одновременно воспроизводится и управляет ртом через Kasamila SDK, без второго плеера. Необязательная камера остаётся локальной; это не готовая связь WebRTC между людьми и не PSTN.', 'Перебивание удаляет старую очередь. Ручная очистка не гарантирует остановку генерации у провайдера. End закрывает транспорт, уничтожает аватар и запрашивает авторизованное завершение Runtime. Тишина не останавливает оплату; проверяйте подтверждение.'],
      ['Запустите relay с одним агентом или защищённым PCM bridge. Укажите KASAMILA_OUTPUT_MODE=transparent и packed-matte HLS прозрачного шаблона: CSS-прозрачность обычного видео не подходит.', 'В /public/studio.html создайте комнату и скопируйте временный URL. Добавьте Browser Source в OBS либо Streamlabs Desktop; это альтернативные оболочки.', 'Через Interact нажмите Enable audio перед Start в студии. Микрофон захватывает студия, аватаром управляют только ответы. Не дублируйте звук браузера захватом звука рабочего стола.', 'FIFO принимает четыре полных файла, каждый до 3 MiB и 30 секунд. Interrupt удаляет старые элементы. Развлечения, чат, торговля и игры используют разные раскладки одного компонента. Необязательный OBS WebSocket v5 переключает настоящую Program Scene, но не обещает такой же RPC Streamlabs Desktop.', 'События Streamlabs можно проверять в студии; сообщения донатов не превращаются автоматически в инструкции или речь. Скрытие, отключение, разрыв связи и End завершают сеанс; возврат видимости не запускает оплату. Проверяйте завершение; при аварии остаётся срок аренды.']
    ],
    notes: ['Рабочий пример не является сертификацией провайдера или гарантией фонемной точности. Добавьте вход, права на шаблоны и инструменты, согласие и HTTPS/WSS; проверьте реальные диалоги.', 'Единый компонент — не четыре готовых бизнес-продукта. Нужны проверка Origin, квоты и модерация, а также реальные испытания прозрачности, очереди, переходов и завершения.'],
    labels: ['Реализация', 'Ограничения и приёмка', 'Код и протоколы', 'Markdown / чтение ИИ']
  },
  es: {
    titles: ['ElevenLabs + Kasamila: atención por videollamada con voz e imagen unificadas', 'OBS + Kasamila + Streamlabs: un anfitrión digital reutilizable para directos'],
    summaries: ['Conserva tu Agent de ElevenLabs y haz visibles sus respuestas: un solo audio alimenta la reproducción y el movimiento de boca.', 'Transparencia, entrada de audio, cola, interrupción, escenas y cierre explícito comparten un componente.'],
    steps: [
      ['Configura el Agent existente de ElevenLabs: base de conocimientos, reglas, herramientas autorizadas y escalado humano. El avatar no sustituye esa lógica.', 'Ejecuta npm ci y copia .env.example a .env. Guarda en el servidor PROVIDER=elevenlabs, ELEVENLABS_API_KEY, ELEVENLABS_AGENT_ID y los parámetros Kasamila con el descriptor multimedia exacto. Selecciona PCM de entrada y salida.', 'Ejecuta npm start y abre /public/video-call.html. Start habilita el audio y solicita el micrófono. El servidor obtiene la URL firmada de ElevenLabs; ni ella ni las claves permanentes se entregan al navegador.', 'El micrófono solo llega al agente. Su respuesta PCM se reproduce y anima la boca mediante el mismo SDK Kasamila, sin otro reproductor. La cámara opcional queda local; no es una llamada WebRTC entre personas ni un servicio PSTN completo.', 'Al hablar se descarta la reproducción antigua. Vaciar la cola manualmente no garantiza detener la generación remota. End cierra el transporte, destruye el avatar y solicita terminar Runtime. El silencio no detiene la facturación: comprueba la confirmación.'],
      ['Inicia el relay con un agente o el puente PCM autenticado. Usa KASAMILA_OUTPUT_MODE=transparent y HLS packed-matte de una plantilla transparente; la opacidad CSS no basta.', 'Abre /public/studio.html, crea una sala y copia la URL temporal. Añádela a Browser Source de OBS o Streamlabs Desktop; son anfitriones alternativos.', 'En Interact pulsa Enable audio antes de Start en el estudio. El micrófono se captura allí y solo las respuestas animan al avatar. Evita capturar también el mismo audio de escritorio.', 'La cola FIFO admite cuatro archivos completos, de hasta 3 MiB y 30 segundos cada uno. Interrupt descarta elementos viejos. Entretenimiento, chat, comercio y juegos son diseños de un solo anfitrión. OBS WebSocket v5 opcional cambia la Program Scene real, sin atribuir ese RPC a Streamlabs Desktop.', 'Los eventos opcionales de Streamlabs se revisan antes de usarse; el texto de donaciones nunca se convierte automáticamente en instrucciones o voz. Ocultar, desactivar, desconectar o End termina la sesión; mostrarla no reinicia el cobro. Verifica el cierre; un fallo del equipo depende aún del vencimiento del arrendamiento.']
    ],
    notes: ['Este ejemplo ejecutable no certifica al proveedor ni garantiza precisión fonética. Añade acceso, autorización, consentimiento, controles de herramientas y HTTPS/WSS; valida llamadas reales.', 'Un componente común no son cuatro productos terminados. Añade comprobación de origen, cuotas y moderación; prueba transparencia, colas, transiciones y cierre en tu instalación.'],
    labels: ['Implementación', 'Límites y aceptación', 'Código y protocolos', 'Lectura Markdown / IA']
  },
  it: {
    titles: ['ElevenLabs + Kasamila: assistenza in videochiamata con voce e immagine unite', 'OBS + Kasamila + Streamlabs: un unico avatar conduttore per le dirette'],
    summaries: ['Mantieni il tuo Agent ElevenLabs: lo stesso audio riproduce la risposta e guida la bocca dell’avatar.', 'Sorgente trasparente, ingresso audio, coda, interruzione, scene e chiusura esplicita in un componente.'],
    steps: [
      ['Configura l’Agent ElevenLabs esistente con conoscenze, istruzioni, strumenti autorizzati e passaggio a un operatore. L’avatar non sostituisce la logica del servizio.', 'Esegui npm ci e copia .env.example in .env. Imposta solo sul server PROVIDER=elevenlabs, ELEVENLABS_API_KEY, ELEVENLABS_AGENT_ID e i parametri Kasamila con il descrittore multimediale esatto. Scegli PCM in ingresso e uscita.', 'Avvia npm start e apri /public/video-call.html. Start sblocca l’audio e richiede il microfono. Il server ottiene l’URL firmato ElevenLabs; URL e chiavi permanenti restano fuori dal browser.', 'Il microfono va soltanto all’agente. Il PCM della risposta viene riprodotto e anima la bocca dallo stesso SDK Kasamila, senza un secondo lettore. La videocamera facoltativa resta locale; non è un servizio WebRTC tra persone o PSTN completo.', 'Quando l’utente interviene, la vecchia riproduzione viene scartata. Svuotare manualmente la coda non garantisce l’arresto della generazione remota. End chiude il trasporto, distrugge l’avatar e richiede la fine autorizzata di Runtime. Il silenzio non ferma gli addebiti: verifica la conferma.'],
      ['Avvia il relay con un agente o il ponte PCM autenticato. Imposta KASAMILA_OUTPUT_MODE=transparent e HLS packed-matte della versione trasparente; l’opacità CSS non sostituisce un vero sfondo trasparente.', 'Apri /public/studio.html, crea una stanza e copia l’URL temporaneo. Usalo come Browser Source in OBS oppure Streamlabs Desktop: sono alternative.', 'Con Interact premi Enable audio prima di Start nello studio. Lo studio acquisisce il microfono; solo le risposte animano l’avatar. Evita la doppia cattura dell’audio browser e desktop.', 'La coda FIFO accetta quattro file completi, ciascuno entro 3 MiB e 30 secondi. Interrupt scarta gli elementi precedenti. Intrattenimento, chat, commercio e giochi sono layout dello stesso host. L’OBS WebSocket v5 opzionale cambia la vera Program Scene, senza promettere lo stesso RPC in Streamlabs Desktop.', 'Gli eventi Streamlabs opzionali sono riepiloghi da approvare, mai messaggi di donazione pronunciati o inseriti automaticamente nei prompt. Nascondere, disattivare, disconnettere o End chiude la sessione; mostrarla non riavvia gli addebiti. Controlla la chiusura; un guasto dipende ancora dalla scadenza della concessione.']
    ],
    notes: ['L’esempio eseguibile non è una certificazione del fornitore né una garanzia fonetica. Aggiungi accesso, autorizzazioni, consenso e HTTPS/WSS; verifica conversazioni e interruzioni reali.', 'Un host comune non equivale a quattro prodotti completi. Servono controlli dell’origine, quote, moderazione e prove reali di trasparenza, code, transizioni e chiusura.'],
    labels: ['Implementazione', 'Limiti e verifica', 'Codice e protocolli', 'Lettura Markdown / IA']
  }
};
Object.assign(languages, {
  ar: {
    titles: ['ElevenLabs + Kasamila: خدمة عملاء بمكالمة فيديو ومسار موحّد للصوت والصورة', 'OBS + Kasamila + Streamlabs: مكوّن مقدّم رقمي واحد للبث المباشر'],
    summaries: ['احتفظ بوكيل ElevenLabs الحالي وأضف شخصية مرئية؛ الصوت نفسه يشغّل الرد وحركة الفم.', 'عرض شفاف وإدخال صوت وطابور تشغيل ومقاطعة ومشاهد وإنهاء واضح للجلسة في مكوّن واحد.'],
    steps: [
      ['اضبط وكيل ElevenLabs الحالي وقاعدة المعرفة وتعليمات الخدمة والأدوات المصرّح بها والتحويل إلى موظف. الشخصية لا تستبدل منطق العمل.', 'نفّذ npm ci وانسخ .env.example إلى .env. ضع PROVIDER=elevenlabs وELEVENLABS_API_KEY وELEVENLABS_AGENT_ID وإعدادات Kasamila ووصف الوسائط المطابق على الخادم فقط. اختر PCM للإدخال والإخراج.', 'شغّل npm start وافتح /public/video-call.html. اضغط Start لتفعيل الصوت والسماح بالميكروفون. يحصل الخادم على رابط ElevenLabs الموقّع؛ لا يصل هذا الرابط ولا المفاتيح الدائمة إلى المتصفح.', 'يصل الميكروفون إلى الوكيل فقط. تُرسل عينات PCM الفعلية للرد إلى Kasamila لتشغيل الصوت وتحريك الفم معاً دون مشغّل ثانٍ. معاينة الكاميرا اختيارية ومحلية؛ ليست هذه خدمة WebRTC بشرية أو PSTN مكتملة.', 'المقاطعة تلغي التشغيل القديم. مسح الطابور يدوياً لا يضمن توقف التوليد البعيد. End يغلق الاتصال ويدمّر الشخصية ويطلب إنهاء Runtime المصرّح به. الصمت لا يوقف الفوترة؛ تحقق من تأكيد الإنهاء.'],
      ['شغّل relay مع وكيل أو جسر PCM موثّق. اضبط KASAMILA_OUTPUT_MODE=transparent ووصف packed-matte HLS لقالب شفاف؛ شفافية CSS ليست بديلاً.', 'افتح /public/studio.html وأنشئ غرفة وانسخ رابط العرض المؤقت. أضفه إلى Browser Source في OBS أو Streamlabs Desktop؛ هما خياران بديلان.', 'من Interact اضغط Enable audio قبل Start في الاستوديو. يُلتقط الميكروفون في الاستوديو ولا تحرّك الشخصية إلا الردود. تجنّب التقاط صوت المتصفح وسطح المكتب مرتين.', 'يسمح FIFO بأربعة ملفات كاملة، كل منها حتى 3 MiB و30 ثانية. Interrupt يلغي العناصر القديمة. الترفيه والدردشة والتجارة والألعاب تخطيطات لنفس المكوّن. يمكن لـ OBS WebSocket v5 الاختياري تبديل Program Scene الحقيقية، دون ادعاء نفس RPC في Streamlabs Desktop.', 'تظهر أحداث Streamlabs الاختيارية للمراجعة البشرية، ولا تصبح رسائل التبرعات تعليمات أو كلاماً آلياً. الإخفاء أو التعطيل أو قطع الاتصال أو End ينهي الجلسة؛ إظهار المصدر لا يعيد الفوترة تلقائياً. تأكد من الإنهاء؛ فشل الجهاز يظل مرتبطاً بانتهاء مدة التأجير.']
    ],
    notes: ['هذا مثال قابل للتشغيل وليس اعتماداً من المزوّد أو ضماناً للدقة الصوتية. أضف تسجيل الدخول والصلاحيات والموافقة وHTTPS/WSS واختبر الحسابات والمحادثات الحقيقية.', 'مكوّن واحد لا يعني أربعة منتجات أعمال مكتملة. أضف فحص Origin والحصص والإشراف واختبر الشفافية والطوابير والانتقالات والإنهاء في بيئتك.'],
    labels: ['خطوات التنفيذ', 'الحدود والقبول', 'الكود والبروتوكولات', 'قراءة Markdown والذكاء الاصطناعي']
  },
  ja: {
    titles: ['ElevenLabs + Kasamila：音声と映像を同じ経路で扱うビデオ客服', 'OBS + Kasamila + Streamlabs：共通コンポーネントでデジタル司会の配信'],
    summaries: ['既存の ElevenLabs Agent を維持し、返答に見えるアバターを追加。再生と口の動きは同じ音声を使います。', '透明なブラウザソース、音声入力、キュー、割り込み、シーン、明示的な終了を一つのホストにまとめます。'],
    steps: [
      ['既存 Agent の知識ベース、客服指示、許可されたツール、人への引き継ぎを設定します。アバターは業務ロジックを置き換えません。', 'npm ci を実行し .env.example を .env にコピー。PROVIDER=elevenlabs、ELEVENLABS_API_KEY、ELEVENLABS_AGENT_ID、Kasamila 設定と一致する媒体記述子をサーバーだけに設定し、入出力は PCM にします。', 'npm start 後 /public/video-call.html を開き、Start で音声とマイクを許可。サーバーが署名付き ElevenLabs URL を取得し、その URL と永久キーをブラウザへ渡しません。', 'マイクは Agent だけに送信。返答の実際の PCM を同じ Kasamila SDK で再生し口を動かし、別プレイヤーは使いません。任意のカメラはローカル表示のみ。人同士の WebRTC 通話や PSTN の完成サービスではありません。', '話し始めると古い再生を破棄します。手動キュー消去だけでは上流生成の停止を保証しません。End で接続を閉じ、アバターを destroy し認可済み Runtime 終了を要求。無音は課金停止ではなく、終了確認が必要です。'],
      ['一つの Agent または認証済み PCM bridge で relay を起動。KASAMILA_OUTPUT_MODE=transparent と対応する packed-matte HLS を使い、CSS の透明度で代用しません。', '/public/studio.html でルームを作り一時 URL をコピー。OBS または Streamlabs Desktop の Browser Source に追加。二つは代替ホストです。', 'Interact で Enable audio を押してから studio の Start。マイクは studio 側で取得し返答だけでアバターを動かします。ブラウザ音声とデスクトップ音声の二重収録を避けます。', 'FIFO は完全ファイル四件、各 3 MiB / 30 秒まで。Interrupt は旧項目を破棄。娯楽、チャット、商取引、ゲームは同じホストのレイアウトです。任意の OBS WebSocket v5 は実際の Program Scene を変更しますが、Streamlabs Desktop の同等 RPC を約束しません。', '任意の Streamlabs イベントは人が確認する要約になり、投げ銭本文を自動的に指示や発話にしません。非表示、無効化、切断、End で終了し、再表示では自動課金再開しません。終了確認を残し、機器障害時はリース期限に依存します。']
    ],
    notes: ['実行可能な例であり、プロバイダー認証や音素精度の保証ではありません。ログイン、権限、同意、HTTPS/WSS を追加し、実アカウントで会話と割り込みを確認してください。', '共通ホストは四つの完成業務製品ではありません。Origin 確認、割当、モデレーションを追加し、透明表示、キュー、転場、終了を実環境で検証してください。'],
    labels: ['実装手順', '範囲と検証', 'コードとプロトコル', 'Markdown / AI 閲覧']
  },
  ko: {
    titles: ['ElevenLabs + Kasamila: 음성과 화면을 하나로 연결하는 영상 고객 상담', 'OBS + Kasamila + Streamlabs: 공통 컴포넌트로 디지털 진행자 방송하기'],
    summaries: ['기존 ElevenLabs Agent를 유지하면서 보이는 아바타를 추가합니다. 재생과 입 움직임은 같은 응답 오디오를 사용합니다.', '투명 브라우저 소스, 음성 입력, 큐, 중단, 장면과 명시적 종료를 하나의 호스트에서 제공합니다.'],
    steps: [
      ['기존 Agent의 지식 기반, 상담 지침, 승인된 도구와 사람에게 넘기는 절차를 설정합니다. 아바타는 업무 로직을 대체하지 않습니다.', 'npm ci 실행 후 .env.example을 .env로 복사합니다. PROVIDER=elevenlabs, ELEVENLABS_API_KEY, ELEVENLABS_AGENT_ID 및 Kasamila 설정과 정확한 미디어 설명자를 서버에만 저장하고 입출력은 PCM으로 선택합니다.', 'npm start 후 /public/video-call.html을 엽니다. Start로 오디오와 마이크를 허용합니다. 서명된 ElevenLabs URL은 서버에서 발급받으며 URL과 영구 키를 브라우저에 전달하지 않습니다.', '마이크는 Agent에만 전달됩니다. 실제 응답 PCM을 Kasamila SDK가 재생하고 입 움직임에도 사용하므로 두 번째 플레이어를 추가하지 않습니다. 선택 카메라는 로컬 미리보기이며 사람 간 WebRTC 또는 PSTN 완성 서비스가 아닙니다.', '끼어들기는 오래된 재생을 폐기합니다. 수동 큐 비우기가 원격 생성 중단을 보장하지는 않습니다. End는 연결 종료, 아바타 destroy와 승인된 Runtime 종료를 요청합니다. 무음은 과금 종료가 아니므로 확인이 필요합니다.'],
      ['Agent 하나 또는 인증된 PCM bridge로 relay를 시작합니다. KASAMILA_OUTPUT_MODE=transparent와 투명 템플릿의 packed-matte HLS를 사용하며 CSS 투명도로 대체하지 않습니다.', '/public/studio.html에서 방을 만들고 임시 URL을 복사합니다. OBS 또는 Streamlabs Desktop의 Browser Source에 넣습니다. 두 앱은 대체 호스트입니다.', 'Interact에서 Enable audio를 누른 뒤 studio에서 Start합니다. 마이크는 studio가 수집하고 Agent 응답만 아바타를 구동합니다. 브라우저와 데스크톱의 같은 음성을 이중 캡처하지 않습니다.', 'FIFO는 전체 파일 네 개, 각각 3 MiB 및 30초까지 허용합니다. Interrupt는 오래된 항목을 폐기합니다. 엔터테인먼트, 채팅, 상거래, 게임은 같은 호스트의 레이아웃입니다. 선택 OBS WebSocket v5는 실제 Program Scene을 바꾸지만 Streamlabs Desktop의 같은 RPC를 주장하지 않습니다.', '선택 Streamlabs 이벤트는 운영자 확인용 요약이며 후원 본문을 자동 프롬프트나 발화로 바꾸지 않습니다. 숨김, 비활성화, 연결 끊김 또는 End로 종료되고 다시 표시해도 자동 과금이 시작되지 않습니다. 종료 확인을 보관하며 장비 장애는 임대 만료에 의존합니다.']
    ],
    notes: ['실행 가능한 예제이지 공급자 인증이나 음소 정확도 보장이 아닙니다. 로그인, 권한, 동의와 HTTPS/WSS를 추가하고 실제 계정의 대화와 중단을 검증하세요.', '공통 호스트는 완성된 네 가지 업무 제품이 아닙니다. Origin 검사, 할당량과 검토를 추가하고 실제 방송에서 투명도, 큐, 전환과 종료를 시험하세요.'],
    labels: ['구현 절차', '범위와 검증', '코드와 프로토콜', 'Markdown / AI 읽기']
  },
  th: {
    titles: ['ElevenLabs + Kasamila: บริการลูกค้าแบบวิดีโอด้วยเสียงและภาพในเส้นทางเดียว', 'OBS + Kasamila + Streamlabs: คอมโพเนนต์ผู้ดำเนินรายการดิจิทัลสำหรับไลฟ์'],
    summaries: ['ใช้ Agent เดิมของ ElevenLabs และเพิ่มอวตารที่มองเห็นได้ เสียงตอบเดียวกันใช้ทั้งเล่นเสียงและขยับปาก', 'ภาพโปร่งใส อินพุตเสียง คิว การขัดจังหวะ ฉาก และการจบเซสชันชัดเจนในคอมโพเนนต์เดียว'],
    steps: [
      ['ตั้งค่า Agent เดิม ทั้งฐานความรู้ คำสั่งบริการ เครื่องมือที่ได้รับอนุญาต และการส่งต่อคน อวตารไม่ได้แทนตรรกะธุรกิจ', 'รัน npm ci แล้วคัดลอก .env.example เป็น .env เก็บ PROVIDER=elevenlabs, ELEVENLABS_API_KEY, ELEVENLABS_AGENT_ID และค่า Kasamila พร้อม media descriptor ที่ตรงกันไว้ฝั่งเซิร์ฟเวอร์เท่านั้น เลือก PCM ทั้งเข้าและออก', 'รัน npm start เปิด /public/video-call.html กด Start เพื่อเปิดเสียงและอนุญาตไมโครโฟน เซิร์ฟเวอร์รับ URL ที่ลงนามจาก ElevenLabs โดยไม่ส่ง URL นี้หรือคีย์ถาวรให้เบราว์เซอร์', 'ไมโครโฟนส่งให้ Agent เท่านั้น PCM คำตอบจริงเข้า SDK Kasamila เพื่อเล่นและขยับปากร่วมกัน ไม่เพิ่มเครื่องเล่นเสียงอีกตัว กล้องเสริมเป็นตัวอย่างในเครื่อง ไม่ใช่ WebRTC ระหว่างคนหรือบริการ PSTN ที่เสร็จสมบูรณ์', 'เมื่อพูดแทรกให้ทิ้งเสียงเก่า การล้างคิวด้วยมือไม่รับประกันหยุดสร้างเสียงบนแพลตฟอร์ม End ปิดการเชื่อมต่อ destroy อวตารและขอจบ Runtime ที่ได้รับอนุญาต ความเงียบไม่หยุดค่าใช้จ่าย ต้องตรวจคำยืนยัน'],
      ['เริ่ม relay ด้วย Agent หนึ่งตัวหรือ PCM bridge ที่ยืนยันสิทธิ์ ตั้ง KASAMILA_OUTPUT_MODE=transparent และ packed-matte HLS ของเทมเพลตโปร่งใส CSS opacity ใช้แทนไม่ได้', 'เปิด /public/studio.html สร้างห้องและคัดลอก URL ชั่วคราว ใส่ใน Browser Source ของ OBS หรือ Streamlabs Desktop ทั้งสองเป็นโฮสต์ทางเลือก', 'ใช้ Interact กด Enable audio ก่อน Start ใน studio ไมโครโฟนเก็บที่ studio และเฉพาะคำตอบขับอวตาร หลีกเลี่ยงรับเสียงเบราว์เซอร์ซ้ำกับเสียงเดสก์ท็อป', 'คิว FIFO รับไฟล์สมบูรณ์สี่ไฟล์ แต่ละไฟล์ไม่เกิน 3 MiB และ 30 วินาที Interrupt ทิ้งรายการเก่า บันเทิง แชต ค้าขาย และเกมเป็นเลย์เอาต์ของโฮสต์เดียว OBS WebSocket v5 เสริมเปลี่ยน Program Scene จริง แต่ไม่ได้อ้าง RPC เดียวกันของ Streamlabs Desktop', 'อีเวนต์ Streamlabs เสริมเป็นสรุปให้ผู้ดูแลตรวจ ไม่เปลี่ยนข้อความบริจาคเป็นคำสั่งหรือเสียงอัตโนมัติ ซ่อน ปิดใช้งาน หลุด หรือ End จบเซสชัน การแสดงใหม่ไม่เริ่มคิดเงินอัตโนมัติ ตรวจการจบ หากเครื่องพังยังขึ้นกับเวลาหมดอายุของสิทธิ์']
    ],
    notes: ['นี่คือตัวอย่างที่รันได้ ไม่ใช่การรับรองแพลตฟอร์มหรือรับประกันความแม่นยำหน่วยเสียง เพิ่มล็อกอิน สิทธิ์ ความยินยอม HTTPS/WSS และทดสอบบทสนทนาจริง', 'โฮสต์ร่วมไม่ใช่สี่ผลิตภัณฑ์สำเร็จ เพิ่มตรวจ Origin โควตาและการกลั่นกรอง แล้วทดสอบโปร่งใส คิว เปลี่ยนฉากและจบจริง'],
    labels: ['ขั้นตอนใช้งาน', 'ขอบเขตและตรวจรับ', 'โค้ดและโปรโตคอล', 'อ่าน Markdown / AI']
  },
  ms: {
    titles: ['ElevenLabs + Kasamila: khidmat pelanggan panggilan video dengan suara dan visual sehala', 'OBS + Kasamila + Streamlabs: satu hos avatar untuk siaran langsung'],
    summaries: ['Kekalkan Agent ElevenLabs sedia ada dan tambah avatar; audio jawapan yang sama digunakan untuk main balik dan gerakan mulut.', 'Paparan telus, input audio, baris gilir, gangguan, adegan dan penamatan jelas berkongsi satu komponen.'],
    steps: [
      ['Konfigurasikan Agent sedia ada: pangkalan pengetahuan, arahan servis, alat dibenarkan dan eskalasi manusia kekal di situ. Avatar tidak menggantikan logik perniagaan.', 'Jalankan npm ci dan salin .env.example ke .env. Simpan PROVIDER=elevenlabs, ELEVENLABS_API_KEY, ELEVENLABS_AGENT_ID serta tetapan Kasamila dan deskriptor media sepadan pada pelayan sahaja. Pilih PCM masuk dan keluar.', 'Jalankan npm start dan buka /public/video-call.html. Start membuka audio serta meminta mikrofon. Pelayan mendapat URL ElevenLabs bertandatangan; URL ini dan kunci kekal tidak dihantar ke pelayar.', 'Mikrofon hanya ke Agent. PCM jawapan sebenar dimainkan dan menggerakkan mulut melalui SDK Kasamila yang sama tanpa pemain kedua. Kamera pilihan kekal tempatan; ini bukan panggilan manusia WebRTC atau servis PSTN lengkap.', 'Celahan membuang main balik lama. Mengosongkan giliran secara manual tidak menjamin penjanaan jauh berhenti. End menutup pengangkutan, destroy avatar dan meminta tamat Runtime yang dibenarkan. Senyap tidak menghentikan bil; periksa pengesahan.'],
      ['Mulakan relay dengan satu Agent atau jambatan PCM disahkan. Tetapkan KASAMILA_OUTPUT_MODE=transparent dan packed-matte HLS templat telus; kelegapan CSS bukan pengganti.', 'Buka /public/studio.html, cipta bilik dan salin URL sementara. Tambah Browser Source dalam OBS atau Streamlabs Desktop; kedua-duanya hos alternatif.', 'Melalui Interact klik Enable audio sebelum Start dalam studio. Mikrofon ditangkap di studio dan hanya jawapan menggerakkan avatar. Elak tangkapan audio pelayar dan desktop berganda.', 'FIFO menerima empat fail lengkap, setiap satu <=3 MiB dan <=30 saat. Interrupt membuang item lama. Hiburan, sembang, dagang dan permainan ialah susun atur hos sama. OBS WebSocket v5 pilihan menukar Program Scene sebenar, bukan dakwaan RPC sama pada Streamlabs Desktop.', 'Acara Streamlabs pilihan menjadi ringkasan untuk semakan, tidak menjadikan mesej derma arahan atau ucapan automatik. Sembunyi, nyahaktif, putus atau End menamatkan sesi; paparan semula tidak memulakan bil. Periksa penamatan; kerosakan mesin masih bergantung pada tamat tempoh pajakan.']
    ],
    notes: ['Contoh boleh dijalankan ini bukan pensijilan pembekal atau jaminan fonem. Tambah log masuk, kebenaran, persetujuan dan HTTPS/WSS; uji akaun serta perbualan sebenar.', 'Satu hos bukan empat produk perniagaan siap. Tambah semakan Origin, kuota dan moderasi; uji ketelusan, giliran, peralihan dan penamatan sebenar.'],
    labels: ['Pelaksanaan', 'Had dan penerimaan', 'Kod dan protokol', 'Bacaan Markdown / AI']
  },
  vi: {
    titles: ['ElevenLabs + Kasamila: chăm sóc khách hàng qua video với âm thanh và hình ảnh thống nhất', 'OBS + Kasamila + Streamlabs: một thành phần người dẫn số cho livestream'],
    summaries: ['Giữ Agent ElevenLabs hiện có, thêm avatar nhìn thấy được; cùng âm thanh trả lời dùng để phát và điều khiển miệng.', 'Nguồn trong suốt, đầu vào âm thanh, hàng đợi, ngắt, cảnh và kết thúc rõ ràng trong một thành phần.'],
    steps: [
      ['Cấu hình Agent hiện có với cơ sở tri thức, hướng dẫn dịch vụ, công cụ được phép và chuyển tiếp con người. Avatar không thay thế logic nghiệp vụ.', 'Chạy npm ci và sao chép .env.example thành .env. Chỉ đặt PROVIDER=elevenlabs, ELEVENLABS_API_KEY, ELEVENLABS_AGENT_ID cùng cấu hình Kasamila và mô tả media khớp trên máy chủ. Chọn PCM đầu vào và đầu ra.', 'Chạy npm start, mở /public/video-call.html. Start mở âm thanh và yêu cầu mic. Máy chủ lấy URL ElevenLabs đã ký; URL đó và khóa vĩnh viễn không được gửi tới trình duyệt.', 'Mic chỉ đến Agent. PCM phản hồi thật được cùng SDK Kasamila phát và điều khiển miệng, không thêm trình phát thứ hai. Camera tùy chọn chỉ xem tại máy; đây không phải cuộc gọi WebRTC giữa người hoặc dịch vụ PSTN hoàn chỉnh.', 'Nói chen loại bỏ phần phát cũ. Xóa hàng đợi thủ công không đảm bảo dừng sinh âm thanh từ xa. End đóng kết nối, destroy avatar và yêu cầu kết thúc Runtime có quyền. Im lặng không ngừng tính phí; cần kiểm tra xác nhận.'],
      ['Khởi động relay bằng một Agent hoặc cầu PCM xác thực. Đặt KASAMILA_OUTPUT_MODE=transparent và packed-matte HLS của mẫu trong suốt; độ mờ CSS không thay thế được.', 'Mở /public/studio.html, tạo phòng và sao chép URL tạm. Thêm vào Browser Source của OBS hoặc Streamlabs Desktop; chúng là hai lựa chọn chủ khác nhau.', 'Qua Interact bấm Enable audio trước Start trong studio. Mic được thu tại studio và chỉ phản hồi điều khiển avatar. Không thu lặp cùng âm thanh từ trình duyệt và desktop.', 'FIFO cho bốn tệp hoàn chỉnh, mỗi tệp tối đa 3 MiB và 30 giây. Interrupt bỏ mục cũ. Giải trí, trò chuyện, thương mại và game là bố cục của cùng host. OBS WebSocket v5 tùy chọn đổi Program Scene thật, không khẳng định RPC tương tự cho Streamlabs Desktop.', 'Sự kiện Streamlabs tùy chọn là bản tóm tắt để người vận hành duyệt, không tự biến lời nhắn quyên góp thành lệnh hay lời nói. Ẩn, vô hiệu, mất kết nối hoặc End kết thúc phiên; hiện lại không tự bật tính phí. Kiểm tra xác nhận; máy hỏng vẫn phụ thuộc hết hạn thuê.']
    ],
    notes: ['Mẫu chạy được không phải chứng nhận nhà cung cấp hoặc bảo đảm độ chính xác âm vị. Bổ sung đăng nhập, quyền, đồng ý và HTTPS/WSS; kiểm thử hội thoại thật.', 'Một host không phải bốn sản phẩm nghiệp vụ hoàn chỉnh. Thêm kiểm tra Origin, hạn mức và kiểm duyệt; thử độ trong suốt, hàng đợi, chuyển cảnh và kết thúc thật.'],
    labels: ['Triển khai', 'Giới hạn và nghiệm thu', 'Mã và giao thức', 'Đọc Markdown / AI']
  },
  hi: {
    titles: ['ElevenLabs + Kasamila: एक ऑडियो पथ से आवाज़ और दृश्य वाला वीडियो ग्राहक समर्थन', 'OBS + Kasamila + Streamlabs: लाइव प्रसारण के लिए एक साझा डिजिटल होस्ट'],
    summaries: ['मौजूदा ElevenLabs Agent रखें और दिखने वाला अवतार जोड़ें; वही उत्तर ऑडियो प्लेबैक और मुँह की गति चलाता है।', 'पारदर्शी Browser Source, ऑडियो इनपुट, कतार, बाधा, दृश्य और स्पष्ट सत्र समाप्ति एक घटक में।'],
    steps: [
      ['मौजूदा Agent में ज्ञान आधार, सेवा निर्देश, अधिकृत टूल और मानव सहायता का मार्ग रखें। अवतार व्यावसायिक तर्क का विकल्प नहीं है।', 'npm ci चलाएँ और .env.example को .env में कॉपी करें। PROVIDER=elevenlabs, ELEVENLABS_API_KEY, ELEVENLABS_AGENT_ID तथा Kasamila सेटिंग और मेल खाता मीडिया विवरण केवल सर्वर पर रखें। इनपुट और आउटपुट PCM चुनें।', 'npm start के बाद /public/video-call.html खोलें। Start ऑडियो सक्रिय करता और माइक्रोफ़ोन अनुमति माँगता है। सर्वर हस्ताक्षरित ElevenLabs URL लेता है; वह URL और स्थायी कुंजियाँ ब्राउज़र में नहीं जातीं।', 'माइक्रोफ़ोन केवल Agent को जाता है। वास्तविक उत्तर PCM को वही Kasamila SDK बजाता और मुँह चलाता है; दूसरा प्लेयर न जोड़ें। वैकल्पिक कैमरा स्थानीय पूर्वावलोकन है, पूर्ण मानव WebRTC कॉल या PSTN सेवा नहीं।', 'बीच में बोलने से पुराना प्लेबैक हटता है। कतार हाथ से साफ़ करना दूर की जनरेशन रोकने की गारंटी नहीं। End कनेक्शन बंद करता, अवतार destroy करता और अधिकृत Runtime समाप्ति माँगता है। मौन बिलिंग नहीं रोकता; पुष्टि देखें।'],
      ['एक Agent या प्रमाणित PCM bridge के साथ relay शुरू करें। KASAMILA_OUTPUT_MODE=transparent और पारदर्शी टेम्पलेट का packed-matte HLS लें; CSS opacity विकल्प नहीं है।', '/public/studio.html में कमरा बनाकर अस्थायी URL कॉपी करें। OBS या Streamlabs Desktop के Browser Source में जोड़ें; ये वैकल्पिक होस्ट हैं।', 'Interact से Enable audio दबाएँ, फिर studio में Start करें। माइक्रोफ़ोन studio लेता है और सिर्फ़ उत्तर अवतार चलाता है। ब्राउज़र और डेस्कटॉप से वही ध्वनि दो बार कैप्चर न करें।', 'FIFO में चार पूर्ण फ़ाइलें, प्रत्येक अधिकतम 3 MiB और 30 सेकंड। Interrupt पुरानी कतार हटाता है। मनोरंजन, चैट, व्यापार और गेम एक होस्ट के लेआउट हैं। वैकल्पिक OBS WebSocket v5 वास्तविक Program Scene बदलता है; Streamlabs Desktop में वही RPC होने का दावा नहीं।', 'वैकल्पिक Streamlabs घटनाएँ संचालक समीक्षा के लिए सारांश हैं, दान संदेशों से स्वतः प्रॉम्प्ट या भाषण नहीं। छिपाने, निष्क्रिय करने, डिस्कनेक्ट या End से सत्र समाप्त; दोबारा दिखाने से बिलिंग स्वतः शुरू नहीं। पुष्टि देखें; मशीन विफल होने पर लीज़ समाप्ति लागू रहती है।']
    ],
    notes: ['चलने वाला उदाहरण प्रदाता प्रमाणन या ध्वनिम सटीकता की गारंटी नहीं है। लॉगिन, अनुमति, सहमति और HTTPS/WSS जोड़ें; वास्तविक बातचीत और बाधा जाँचें।', 'साझा होस्ट चार तैयार व्यापार उत्पाद नहीं है। Origin जाँच, कोटा और मॉडरेशन जोड़ें; वास्तविक पारदर्शिता, कतार, दृश्य परिवर्तन और समाप्ति जाँचें।'],
    labels: ['कार्यान्वयन', 'सीमाएँ और स्वीकृति', 'कोड और प्रोटोकॉल', 'Markdown / AI पठन']
  },
  id: {
    titles: ['ElevenLabs + Kasamila: layanan pelanggan panggilan video dengan satu jalur suara dan visual', 'OBS + Kasamila + Streamlabs: satu komponen pembawa acara digital untuk siaran'],
    summaries: ['Pertahankan Agent ElevenLabs yang ada dan tambahkan avatar; audio balasan yang sama dipakai untuk pemutaran dan gerak mulut.', 'Tampilan transparan, input audio, antrean, interupsi, adegan dan akhir sesi eksplisit dalam satu komponen.'],
    steps: [
      ['Konfigurasikan Agent yang ada: basis pengetahuan, petunjuk layanan, alat berizin dan eskalasi manusia tetap di sana. Avatar tidak menggantikan logika bisnis.', 'Jalankan npm ci dan salin .env.example ke .env. Simpan PROVIDER=elevenlabs, ELEVENLABS_API_KEY, ELEVENLABS_AGENT_ID serta konfigurasi Kasamila dan deskriptor media yang cocok di server saja. Pilih PCM masuk dan keluar.', 'Jalankan npm start lalu buka /public/video-call.html. Start membuka audio dan meminta mikrofon. Server memperoleh URL ElevenLabs bertanda tangan; URL itu dan kunci permanen tidak diberikan ke browser.', 'Mikrofon hanya menuju Agent. PCM balasan nyata diputar sekaligus menggerakkan mulut lewat SDK Kasamila yang sama, tanpa pemutar kedua. Kamera opsional hanya pratinjau lokal; bukan layanan WebRTC antarmanusia atau PSTN lengkap.', 'Menyela membuang pemutaran lama. Mengosongkan antrean secara manual tidak menjamin penghentian generasi jarak jauh. End menutup transport, destroy avatar dan meminta akhir Runtime berizin. Diam bukan penghentian tagihan; periksa konfirmasinya.'],
      ['Mulai relay dengan satu Agent atau jembatan PCM terautentikasi. Atur KASAMILA_OUTPUT_MODE=transparent dan packed-matte HLS templat transparan; opacity CSS bukan pengganti.', 'Buka /public/studio.html, buat ruang dan salin URL sementara. Tambahkan ke Browser Source OBS atau Streamlabs Desktop; keduanya host alternatif.', 'Melalui Interact klik Enable audio sebelum Start di studio. Mikrofon ditangkap di studio dan hanya balasan menggerakkan avatar. Hindari menangkap audio browser dan desktop yang sama dua kali.', 'FIFO menerima empat berkas lengkap, masing-masing <=3 MiB dan <=30 detik. Interrupt membuang item lama. Hiburan, obrolan, niaga dan gim adalah tata letak satu host. OBS WebSocket v5 opsional mengganti Program Scene nyata, tanpa menjanjikan RPC sama di Streamlabs Desktop.', 'Acara Streamlabs opsional menjadi ringkasan untuk ditinjau, bukan otomatis mengubah pesan donasi menjadi instruksi atau ucapan. Menyembunyikan, menonaktifkan, terputus atau End mengakhiri sesi; tampil kembali tidak memulai tagihan otomatis. Periksa akhir; kegagalan mesin masih bergantung pada masa sewa.']
    ],
    notes: ['Contoh yang berjalan bukan sertifikasi penyedia atau jaminan ketepatan fonem. Tambahkan login, izin, persetujuan dan HTTPS/WSS; uji akun dan percakapan nyata.', 'Host bersama bukan empat produk bisnis selesai. Tambahkan pemeriksaan Origin, kuota dan moderasi; uji transparansi, antrean, transisi dan akhir di lingkungan nyata.'],
    labels: ['Implementasi', 'Batas dan penerimaan', 'Kode dan protokol', 'Bacaan Markdown / AI']
  }
});
